// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOpS1K1654PhFMi8E5Rx65tY7wLTfHsww',
    appId: '1:1005328208811:web:0c71aa57f431944226f8ee',
    messagingSenderId: '1005328208811',
    projectId: 'ngoding-chatting-app',
    authDomain: 'ngoding-chatting-app.firebaseapp.com',
    storageBucket: 'ngoding-chatting-app.appspot.com',
    measurementId: 'G-CE946563BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO5nm3DF0e9fh7RiBm25olFBpI7mqBNK4',
    appId: '1:1005328208811:android:2c0e179fa6ed9dc826f8ee',
    messagingSenderId: '1005328208811',
    projectId: 'ngoding-chatting-app',
    storageBucket: 'ngoding-chatting-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6yaLpqVW_erx12BUqR-hjFvX9EBd3gOI',
    appId: '1:1005328208811:ios:88d83e5220d5b9e426f8ee',
    messagingSenderId: '1005328208811',
    projectId: 'ngoding-chatting-app',
    storageBucket: 'ngoding-chatting-app.appspot.com',
    iosClientId:
        '1005328208811-gcslbcg9tc9ugulsmgff3886qlm5offb.apps.googleusercontent.com',
    iosBundleId: 'com.thengoding.chatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6yaLpqVW_erx12BUqR-hjFvX9EBd3gOI',
    appId: '1:1005328208811:ios:384dbf20d4ad40d626f8ee',
    messagingSenderId: '1005328208811',
    projectId: 'ngoding-chatting-app',
    storageBucket: 'ngoding-chatting-app.appspot.com',
    iosClientId:
        '1005328208811-sl67jdobfjb4qqpbgsj6s9dr6pqi3jq8.apps.googleusercontent.com',
    iosBundleId: 'com.thengoding.chatting.chattingApp',
  );
}
